server:
  port: 8080

spring:
  application:
    name: message-scheduler
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    generate-ddl: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  jmx:
    enabled: false
  datasource:
    url: jdbc:${SPRING_DATASOURCE_ID:mysql}://${SPRING_DATASOURCE_HOST:localhost}:${SPRING_DATASOURCE_PORT:3306}/${SPRING_DATASOURCE_DATABASE:message}?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
    username: ${SPRING_DATASOURCE_USERNAME:user_db}
    password: ${SPRING_DATASOURCE_PASSWORD:password_db}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:com.mysql.jdbc.Driver}

  flyway:
    enabled: ${SPRING_FLYWAY_ENABLED:true}
    url: jdbc:${SPRING_DATASOURCE_ID:mysql}://${SPRING_DATASOURCE_HOST:localhost}:${SPRING_DATASOURCE_PORT:3306}/${SPRING_DATASOURCE_DATABASE:message}?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
    user: ${SPRING_DATASOURCE_USERNAME:user_db}
    password: ${SPRING_DATASOURCE_PASSWORD:password_db}
    baseline-on-migrate: true
    check-location: true
    locations: classpath:/db/migration/
